#!/usr/bin/env python3
# gen-seed — data/menu.json → migrations/0002_seed_menu.sql (idempotent upsert).
# A menu change before Part Two = re-run extract-menu, re-run this, new migration number.
import json,sys
d=json.load(open(sys.argv[1],encoding='utf-8'))
def q(v): return 'NULL' if v is None else "'"+str(v).replace("'","''")+"'"
rows=[]
for i in d['items']:
    rows.append("(%s,%s,%s,%d,%s,%s,%s,%s,%s,%s,%d,%d,%d,%s)"%(q(i['id']),q(i['kind']),q(i['cat']),i['pos'],
      q(i['name']['nl']),q(i['name']['en']),q(i['name']['de']),q(i['desc']['nl']),q(i['desc']['en']),q(i['desc']['de']),
      i['price_cents'],i['vat_rate'],1 if i['orderable'] else 0,q(i['orderable_note'] or None)))
out=["-- GENERATED by tools/gen-seed.py from data/menu.json (%s, extracted %s). Do not hand-edit."%(d['source'],d['extracted']),
     "INSERT INTO menu_items (id,kind,cat,pos,name_nl,name_en,name_de,desc_nl,desc_en,desc_de,price_cents,vat_rate,orderable,orderable_note) VALUES"]
out.append(",\n".join(rows))
out.append("ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,cat=excluded.cat,pos=excluded.pos,name_nl=excluded.name_nl,name_en=excluded.name_en,name_de=excluded.name_de,desc_nl=excluded.desc_nl,desc_en=excluded.desc_en,desc_de=excluded.desc_de,price_cents=excluded.price_cents,vat_rate=excluded.vat_rate,orderable=excluded.orderable,orderable_note=excluded.orderable_note,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');")
# per-dish choices become ROWS (schema note: an editor wants to reorder, price and sell out ONE
# option, all row properties). price_cents ships at 0 for everything that exists today.
orows=[]
for i in d['items']:
    for gp,g in enumerate(i.get('options') or []):
        for op,o in enumerate(g['options']):
            orows.append("(%s,%s,%s,%d,%d,%d,%s,%s,%s,%s,%s,%s,%s,0)"%(
              q(i['id']),q(g['id']),q(o['id']),gp,op,1 if g.get('required',True) else 0,q(g['source']),
              q(g['label']['nl']),q(g['label']['en']),q(g['label']['de']),
              q(o['label']['nl']),q(o['label']['en']),q(o['label']['de'])))
if orows:
    out.append("")
    out.append("INSERT INTO item_options (item_id,group_id,option_id,group_pos,option_pos,required,source,group_nl,group_en,group_de,label_nl,label_en,label_de,price_cents) VALUES")
    out.append(",\n".join(orows))
    out.append("ON CONFLICT(item_id,group_id,option_id) DO UPDATE SET group_pos=excluded.group_pos,option_pos=excluded.option_pos,required=excluded.required,source=excluded.source,group_nl=excluded.group_nl,group_en=excluded.group_en,group_de=excluded.group_de,label_nl=excluded.label_nl,label_en=excluded.label_en,label_de=excluded.label_de;")
open(sys.argv[2],'w',encoding='utf-8').write("\n".join(out)+"\n"); print('seed rows',len(rows),'option rows',len(orows))
