#!/usr/bin/env python3
# gen-seed — data/menu.json → migrations/0002_seed_menu.sql (idempotent upsert).
# A menu change before Part Two = re-run extract-menu, re-run this, new migration number.
import json,sys
d=json.load(open(sys.argv[1],encoding='utf-8'))
def q(v): return 'NULL' if v is None else "'"+str(v).replace("'","''")+"'"
rows=[]
for i in d['items']:
    opts=json.dumps(i['options'],ensure_ascii=False,separators=(',',':')) if i.get('options') else None
    rows.append("(%s,%s,%s,%d,%s,%s,%s,%s,%s,%s,%d,%d,%d,%s,%s)"%(q(i['id']),q(i['kind']),q(i['cat']),i['pos'],
      q(i['name']['nl']),q(i['name']['en']),q(i['name']['de']),q(i['desc']['nl']),q(i['desc']['en']),q(i['desc']['de']),
      i['price_cents'],i['vat_rate'],1 if i['orderable'] else 0,q(i['orderable_note'] or None),q(opts)))
out=["-- GENERATED by tools/gen-seed.py from data/menu.json (%s, extracted %s). Do not hand-edit."%(d['source'],d['extracted']),
     "INSERT INTO menu_items (id,kind,cat,pos,name_nl,name_en,name_de,desc_nl,desc_en,desc_de,price_cents,vat_rate,orderable,orderable_note,options_json) VALUES"]
out.append(",\n".join(rows))
out.append("ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,cat=excluded.cat,pos=excluded.pos,name_nl=excluded.name_nl,name_en=excluded.name_en,name_de=excluded.name_de,desc_nl=excluded.desc_nl,desc_en=excluded.desc_en,desc_de=excluded.desc_de,price_cents=excluded.price_cents,vat_rate=excluded.vat_rate,orderable=excluded.orderable,orderable_note=excluded.orderable_note,options_json=excluded.options_json,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');")
open(sys.argv[2],'w',encoding='utf-8').write("\n".join(out)+"\n"); print('seed rows',len(rows))
